### ISSUE TITLE
Header handling for created images and exposures

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#105]
See the comment on the test_data_flow test in tests/pipeline/test_pipeline.py

Go through and make sure that the handling of _raw_header for both images and exposures is all the way we want it to be.  In particular, the raw_header property should return an empty header, not None, if there isn't a header, so that we can handle FITS files that won't like a None header.  Also, make sure that raw header is nowhere getting a dictionary.

**Comment by guynir42** [comment]
Addressed by PR #125
