### ISSUE TITLE
Multiple coadds filepath is not unique

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#141]
For example if making a new coadded image from images 1,2,3 and from images 1,2,3,4 the two coadds would have the same filepath, which is a unique violation. 

Maybe add the filepaths (into a hash) into the coadd filepath?

**Comment by rknop** [comment]
A hash of the filepaths sounds like it would work.  Perhaps make sure to sort them before making the hash so that we don't get two different hashes for what would be the same coadd.

**Comment by guynir42** [comment]
Addressed by #159
