### ISSUE TITLE
Bit flag for pixels outside of aligned image area

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#163]
When we use swarp (or any alignement method) it leaves some pixels missing in the aligned images (outside the area of the image before warping). 

These are currently marked with '1' which is the bit for "bad pixel". I suggest we change this to a dedicated value and make sure alignment methods use the correct bit.

**Comment by guynir42** [comment]
@rknop please suggest a name for this!

**Comment by guynir42** [comment]
After we do this, we should consider what to do with the actual image data for subtractions that have these margins...

Right now, we are "inpainting" the missing data on the reference and using that in the subtraction, which leads to the edges of the image having weird, unsubtracted data. Now, it is true that you should look at the flags and mask out that region, but this isn't a saturated star, it is potentially big regions that have completely un-reasonable values in them for a subtraction. 

I suggest we may want to mask out those values (using NaN??) just so people that load up the image without masking would not be confused about this region. I don't know if there's any reason to keep those pixel values, as they are completely wrong.

**Comment by rknop** [comment]
NaN seems like a good option, but I wouldn't be surprised if it threw some FITS readers for a loop.  For instance, anything that just blindly calculates the median of a whole image will get NaN if any pixels are NaN.

Perhaps just set them to uniform 0.  Anybody looking closely at the image will be able to tell that something's up there (no nose), and they *will* be masked.  And, that won't throw off any statistics on subtraction images.

**Comment by guynir42** [comment]
"out of bounds"

**Comment by guynir42** [comment]
Also, make sure all names are lower case.
