### ISSUE TITLE
Background estimates

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#173]
Right now images are created without an accompanying `bkg_mean_estimate` and `bkg_rms_estimate`. 

We should add this in the preprocessing or in the extraction phase.

**Comment by rknop** [comment]
Going into the extraction phase.

(I needed this for the webap to be sensible, so it's getting rolled in there.)

Near term, will only be implemented for sextractor extraction.

**Comment by guynir42** [comment]
Yeah this is fine. At some point someone will pick up the suite of issues to do with background and clean all of this up.

**Comment by guynir42** [comment]
Addressed by #308
