### ISSUE TITLE
Measurements need PSF photometry

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#222]
I'm not sure how to do that with an arbitrary PSF image. 

It is not super urgent so I'm leaving it for later.

**Comment by rknop** [comment]
My suggestion: look at `models.psf.get_clip()`.  That gets a image-resolution, possibly-normalized cutout of a psf, which can be positioned centered on fractional pixels.  Use that as a weighting function.

The only issue is, right now that's only implemented for psfex.  It would need to be implemented for any other PSF type that we use.  (What is the format of the zogy PSFs?  I think that's the only other one we have right now.)
