### ISSUE TITLE
Get github actions working with docker pull and push

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#24]
Right now when running automated tests in github actions, it rebuilds the docker image every time the test runs.

Ideally, we should be able to use a docker repository (e.g. the github repository!) as a way to cache the docker layers, so it can pull layers that haven't changed, and push ones that have, making the tests run faster.  This turns out to be surprisingly complicated.

**Comment by rknop** [comment]
A github forum question I posted about this (that as of this writing has no answers yet):

https://github.com/orgs/community/discussions/51417

**Comment by guynir42** [comment]
@rknop would you say this is now working properly?

**Comment by rknop** [comment]
Yeah, I think so.  It doesn't actually pull and push on github actions, but it does cache the docker layers, which is more what we want.
