### ISSUE TITLE
Should MD5sum contain the content AND the filepath?

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#243]
Sometimes (in tests, at least) we get identical file contents for different files (e.g., the PSF XML file). 
Would it be reasonable to also have the filepath included in the sum? The filepaths would be unique because they come from different image filenames.

**Comment by rknop** [comment]
I don't think this is necessary.  It adds unnecessary complication that could well cause confusion later.

The purpose of the md5sum is to make sure that contents of the file are correct.  It doesn't matter if two entries have the same md5sum.  We don't (and shouldn't) use the md5sum to distinguish logically distinct things, we should only use it as a signature of the contents.  filepaths by themselves (and also database IDs, but filepaths are all that the archive server knows about) are what we use to distinguish logically distinct things.

This would also complicate all the various operations around md5sums, as we'd have to make sure to append in the filepath to whatever binary blob we were running the md5sum operations on.  Let's keep it simple and have the md5sum just be a checksum of the file contents.

**Comment by guynir42** [comment]
Agreed. I do have to figure out if the MD5sum column is forced to be unique because it is a UUID field. 
We may need to change it to a string instead...

**Comment by rknop** [comment]
Postgres doesn't require UUID fields to be unique.  (I just tried it.)

**Comment by guynir42** [comment]
hmmmm, I will have to try to re-break that test that failed on me before to figure out what was the constraint that gave me trouble.

**Comment by rknop** [comment]
Did we manually add a unique constraint ourselves?

**Comment by guynir42** [comment]
I am closing this for now. If the uniqueness issue comes up we will look into it again.
