### ISSUE TITLE
Add a pixel scale to the database

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#258]
Reason: fwhm is stored in pixels.  For quick looks at image quality, it's helpful to have the seeing in arcseconds.  While we can get this from the instrument class, it'd be nice to be able to do this entirely from the database, and instrument parameters like that are not in the database.

We could create an instruments table in the database with this kind of information.  (That's what I did in lensgrinder.  There, I had a table that stored some basic information about all of the chips of a given detector, and the image table linked to that table; our equivalent is just a string sensor section.)  Alternatively, we could just add a pixel scale to the image model.  From a database point of view, the former is probably preferable, since this will be highly redundant information.

**Comment by guynir42** [comment]
Maybe put it in the WCS?

**Comment by guynir42** [comment]
@rknop I think you may be able to get this from the WCS (the solution must have a pixel scale though it may be saved in the parameters so not directly on the DB). 

Should we maybe add a column to WCS to keep that information? It will be redundant but will be easy to find.
