### ISSUE TITLE
Image delete products test is too slow

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#291]
I'm marking the `models/test_image.py::test_image_products_are_deleted` as a skipped. It takes up way too much time, and I think the reason is because of loading upstreams/downstreams for all the Cutouts and Measurements is just a terrible loop inside a loop (or recursion inside recursion). 

This will probably sort itself out once we move to Cutouts as a single file object, and while there may still be a lot of measurements, the test will probably go faster. 

If that doesn't fix the slowness of the test, we should look into why it is so slow. 

In any case, the test should be reinstated once it is running fast.

**Comment by whohensee** [comment]
I speculate that this  was related to the behavior of Cutouts as a list when running `image.delete_from_disk_and_database`, and it seems that with PR #302 which changed Cutouts to behave as a normal FileOnDiskMixin, this issue has been resolved.
