### ISSUE TITLE
Make sure file exists before inserting into database

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#38]
Need to add a "before_insert" that listens to events for Exposure and Image objects (and maybe others) such that you can't commit the object without having a file exist on disk. 

There should be some consideration whether this works when the data is on a server and doesn't exist locally.

**Comment by rknop** [comment]
We'll need to think about how this interacts with nofile.  (It may be as simple as skipping the check if nofile is true.)  Some tests right now use nofile to make database entries without an associated file.

**Comment by guynir42** [comment]
This is not the expected use for "nofile". I put it in as a way to allow you to make an object and then populate the data and save. 
Right now you cannot commit an image (or other FileOnDiskMixin objects) unless they have a filepath. 
You can spoof the filepath and commit - but that is not what we want. 

The crucial thing is that "nofile" is not saved to the database along with the object. It is only there to help you initialize and object and fill it up before committing. 

I think it should not be possible to add an object without a file, that is the whole point of FileOnDiskMixin. 
The tests are not too hard to modify. In fact, I think I will add a helper function that automatically saves a temporary file for each Image fixture so it would be easier to setup the tests.

**Comment by guynir42** [comment]
OK so what we actually need is to make sure that the MD5 sum is always saved only after the file is saved to the archive. 
If archive is not defined (explicitly set to null in the config) then MD5 is set after saving locally instead. 

Then the only thing to do is make sure MD5 is not null.

**Comment by guynir42** [comment]
@rknop make sure that MD5 is only saved upon the right conditions. 
@guynir42 will add a constraint that makes sure the MD5 (or the extensions MD5) is not null. 
and will also go over the tests to make sure they comply with this.
