### ISSUE TITLE
Calibrate images relative to Gaia

### ISSUE THREAD

**Issue by adamamiller** [c3-time-domain/SeeChange#41]
In addition to astrometry, Gaia provides color information (and for the brightest sources also spectroscopy). It should be possible to calibrate LS4 (or other wide-field survey) photometry using Gaia sources and this should be investigated prior to the start of the survey.

**Comment by guynir42** [comment]
I think this is part of a bigger discussion of "which survey to use for photometric calibration". Having Gaia as an option is a good start but it will definitely be configurable.
