### ISSUE TITLE
Remove SExtractor dependancy 

### ISSUE THREAD

**Issue by adamamiller** [c3-time-domain/SeeChange#43]
It may be possible to remove SExtractor using SEP (https://bids.berkeley.edu/publications/sep-source-extractor-library) or astropy/photutils (https://photutils.readthedocs.io/en/stable/detection.html) so that the pipeline does not rely on SExtractor binary files.

**Comment by guynir42** [comment]
Thanks @adamamiller I was just starting to work on this.

**Comment by guynir42** [comment]
Addressed by #48
