### ISSUE TITLE
Configurable sky subtraction

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#51]
As of the writing of this issue, source extract just does the default sep.Background() sky subtraction.  While this is probably going to work for many extragalactic fields, we need this to be configurable.

We need the ability to flag an image as not needing sky subtraction at all -- either because it's preprocessing pipeline produced sky subtracted images (e.g. there might be an instrument that has a customized process), or because it's a subtraction image.

We also will want the ability to use different sky subtraction algorithms (and, of course, track it in the provenance).  This may just be different parameters passed to sep.Background(), but may also need to be entire different algorithms.  My experience suggests that in crowded galactic fields, the SExtractor sky subtraction oversubtracts quite a bit.  The algorithm of Bijaoui, 1980, A&A, 84, 81 still oversubtracts a bit, but not nearly as much.  (Sky subtraction is very difficult in crowded fields!)

**Comment by guynir42** [comment]
Can we say that sky subtraction is part of the "source extraction" process and that these parameters will join the other steps like finding sources, estimating PSF, inside the same Provenance?

**Comment by guynir42** [comment]
Addressed by #308
