### ISSUE TITLE
Pre-reduced exposures and Provenance

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#66]
What happens when an Exposure is downloaded from an instrument but it already had some data reductions applied to it, in terms of the provenance of those products?

**Comment by guynir42** [comment]
Related to #64

**Comment by rknop** [comment]
I've added a 'proc_type' keyword to the parameters that get set for the "download" (formerly "load_exposure") provenance generated by default for Exposure.  Defaults to proc_type 'raw'.  DECam uses 'raw' and 'instcal'.

Currently in the Swarp PR, `Instrument.get_exposure_provenance()` (which `Exposure.make_provenance()` now calls.)

The DECam code that downloads exposures also sets preproc_bitflag when downloading reduced images.
