### ISSUE TITLE
Remove Enums

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#69]
I've just about had it with Enums under Postgres/SQLAlchemy

Here's a list of things we can't do:
- remove an Enum value, unless you go through a very complicated dance
- rename the text that represents an Enum value (e.g., Sci->sci will not be possible unless you manually do it)
- put the Enum definition in the base class (mixin) and inherit from others, as that breaks the tests where we do `create_table` (this works in alembic, though). 

Here's a counter-proposal:
Use integers, and have a getter/setter lookup table to translate the integers into text. 
Advantages:
- you can easily add values, just make the setter function accept new strings. 
- you can easily rename existing data, just alter the lookup tables. 

Disadvantages:
- if you are looking at the database directly, you will see a number, not a value (e.g., "2" instead of "Bias"). 

That's it. Please discuss.

**Comment by nugent68** [comment]
You can do the integer and then just have a lookup table for it. Gives you some flexibility. This is what we did for the timing on the various parts of the pipeline.

**Comment by guynir42** [comment]
Addressed by #73
