### ISSUE TITLE
Add subdirectories to invent_filename

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#74]
Filesystems can get sad if you put too many files in one directory.  We should add subdirectories to the exposure and image invent_filename methods to partition files into subdirectories (e.g. by instrument, date).  Anything that writes the files (FileOnDiskMixin, but also download routines) should make sure the directory exists before trying to write a file.

**Comment by guynir42** [comment]
@rknop let me know if this is ok to close.
