### ISSUE TITLE
Implement coadd

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#83]
Needed for (at least) building references.  Will also be used to make deeper images.  Need to implement actually doing it, as we as loading the coadded image into the database.

First implementation will shell out to swarp, since that's the implementation we have working.  We can add other algorithms later.

The interface may be the same as what's used for building flats and biases, but swarp is not the right tool for that sort of thing.  (To zeroth order, we want to median images to build flats and biases, but in reality we want to do something more sophisticated.)

**Comment by guynir42** [comment]
Addressed by #159
